services:
  arch:
    image: archlinux:latest
    volumes:
      - ./dist/pkgmate-linux_linux_amd64_v1/pkgmate:/pkgmate:ro
    stdin_open: true
    tty: true

  debian:
    image: debian:latest
    volumes:
      - ./dist/pkgmate-linux_linux_amd64_v1/pkgmate:/pkgmate:ro
    stdin_open: true
    tty: true

  brew:
    image: homebrew/brew:latest
    volumes:
      - ./dist/pkgmate-linux_linux_amd64_v1/pkgmate:/pkgmate:ro
    stdin_open: true
    tty: true
    environment:
      - HOMEBREW_NO_AUTO_UPDATE=1
